name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v3
        name: PHPUnit tests
        with:
          bootstrap: vendor/autoload.php
          configuration: tests/phpunit.xml
          args: --coverage-text
